// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saxpztggtgmpzurvcgxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheHB6dGdndGdtcHp1cnZjZ3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTYwMjEsImV4cCI6MjA3MDQ5MjAyMX0.WU-qjuGrW77TpaQcsQeuDdDTybyXvaX5M_n2uoHclvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});